---
# tasks file for docker-compose
- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: copy file docker-compose on all target hosts
  ansible.builtin.copy:
    src: "{{ sourse_file }}"
    dest: docker-compose/
    mode: "0644"

- name: run docker-compose containers
  community.docker.docker_compose:
    project_src: docker-compose
    files:
      - "docker-compose.yml"
    state: present

