---
# tasks file for docker-compose
- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: copy file docker-compose on all target hosts
  ansible.builtin.copy:
    src: "{{ sourse_file }}"
    dest: docker-compose/
    mode: "0644"

- name: run docker-compose containers
  community.docker.docker_compose:
    project_src: docker-compose
    files:
      - "docker-compose.yml"
    state: present

